config/routes.rb
Rails.application.routes.draw do
  # get 'lists/index'
  # # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get 'lists', to: 'lists#index'
  # get 'lists/new', to: 'lists#new'
  # get 'lists/:id', to: 'lists#show'
  # post 'lists', to: 'lists#create'
  root to: 'lists#index'
  resources :lists, only: [ :index, :new, :show, :create] do
    resources :bookmarks, only: [ :index, :new, :create ]
  end

  resources :bookmarks, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie

  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  before_destroy :check_for_bookmarks?

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true

  def check_for_bookmarks?
    errors.add(:base, "cannot delete movie with a bookmark") unless bookmarks.count == 0
    errors.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: [ :new, :create ]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmarks_params)
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    redirect_to list_path(@book)
  end

  private

  def bookmarks_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
<h4>Add a bookmark to the <%= @list.name %> list</h4>
  <%= simple_form_for([ @list, @bookmark ]) do |f|%>
    <%=f.association :movie %>
    <%=f.label :comment  %>
    <%=f.text_field :comment %>
    <%=f.submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<nav class="navbar navbar-light bg-light fixed-top">
  <span id="empty"></span>
  <span class="navbar-brand mb-0 h1"><%= link_to "New list", new_list_path %></span>
</nav>

<div class="banner home"><h1>Movies</h1></div>

<div class="main-container">
  <h3>What are you going to watch right now?</h3>

    <div class="card-container-flex" >
      <% @lists.each do |list| %>
      <div class="card">
        <div class="card-image">
          <% if list.photo.attached? %>
            <%=  cl_image_tag list.photo.key, alt: "Movie Card" %>
          <% else %>
            <%=  image_tag "list_background.jpg", alt: "Movie Card" %>
          <% end %>
        </div>
        <%= link_to list.name, list %>
      </div>
      <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container">
  <h4>Create a new list</h4>
  <%= simple_form_for @list do |f| %>
    <%= f.input :name, placeholder: 'Drama' %>
    <%= f.input :photo, as: :file %>
    <%= f.submit %>
  <% end %>
</div>

app/views/lists/show.html.erb
<nav class="navbar navbar-light bg-light fixed-top">
  <span id="empty"></span>
  <span class="navbar-brand mb-0 h1"><%= link_to "Lists", root_path %></span>
</nav>


<div class="banner" style="background-image: url(<%= @list.photo.attached? ? cl_image_path(@list.photo.key) : asset_path('list_background.jpg') %>)">
</div>
 <div class="button-bar">
  <div class="btn btn-success">
    <%= link_to "add a movie", new_list_bookmark_path(@list.id) %>
  </div>
</div>

<div class="main-container">
<% @list.bookmarks.each do |bookmark|%>
  <div class="card-container-flex">
    <div class="card">
      <div class="card-image">
      <%= image_tag bookmark.movie.poster_url %>
      </div>
      <div class="title"><%= bookmark.movie.title %></div>
      <div class="overview"><%= bookmark.movie.overview %></div>
    </div>
  <% end %>
  </div>
</div>